### PR TITLE
Makes compatible with webpack

### PR DESCRIPTION
**Pull request by rjmk**
If a fix for #30 is desired, then this would provide it

### CODE REVIEW

**Comment by nelsonic** [comment]
Sounds good @rjmk  👍

**Comment by nelsonic** [comment]
@rjmk do you want to increase the version in package.json and add something in Readme to indicate that this is now WebPack compatible? also, add a couple of keywords to the `package.json` > `keywords` e.g: WebPack, universal ... etc.

**Comment by rjmk** [comment]
Will do! The wifi I'm using is a bit precious about its ports, so will be this evening probably

**Comment by nelsonic** [comment]
@rjmk please assign when ready for merge. 👍 
feel free to `git tag` the version and npm publish when ready. I'm online for the next 10h so will merge within seconds of PR assignment. 😉

**Comment by nelsonic** [comment]
seconds later...

**Comment by rjmk** [comment]
Tagged locally, but I suspect `git push --tags` needs to be done on master

**Comment by rjmk** [comment]
Incredible!

**Comment by nelsonic** [comment]
I've briefly restored the branch so you can push your tags.

**Comment by rjmk** [comment]
Looks like it worked, yay!

**Pull request merged**
